DROP INDEX `idx_evidence_sha_source_control_assessment`;--> statement-breakpoint
DROP INDEX `idx_evidence_dedupe_unscoped`;--> statement-breakpoint
CREATE UNIQUE INDEX `idx_evidence_dedupe_nnn` ON `evidence_artifacts` (`sha256`,`source`,`control_id`,`framework`,`system`) WHERE "evidence_artifacts"."assessment_id" IS NULL AND "evidence_artifacts"."environment" IS NULL AND "evidence_artifacts"."assessment_period" IS NULL AND "evidence_artifacts"."status" NOT IN ('expired', 'purged');--> statement-breakpoint
CREATE UNIQUE INDEX `idx_evidence_dedupe_ann` ON `evidence_artifacts` (`sha256`,`source`,`control_id`,`framework`,`system`,`assessment_id`) WHERE "evidence_artifacts"."assessment_id" IS NOT NULL AND "evidence_artifacts"."environment" IS NULL AND "evidence_artifacts"."assessment_period" IS NULL AND "evidence_artifacts"."status" NOT IN ('expired', 'purged');--> statement-breakpoint
CREATE UNIQUE INDEX `idx_evidence_dedupe_nen` ON `evidence_artifacts` (`sha256`,`source`,`control_id`,`framework`,`system`,`environment`) WHERE "evidence_artifacts"."assessment_id" IS NULL AND "evidence_artifacts"."environment" IS NOT NULL AND "evidence_artifacts"."assessment_period" IS NULL AND "evidence_artifacts"."status" NOT IN ('expired', 'purged');--> statement-breakpoint
CREATE UNIQUE INDEX `idx_evidence_dedupe_nnp` ON `evidence_artifacts` (`sha256`,`source`,`control_id`,`framework`,`system`,`assessment_period`) WHERE "evidence_artifacts"."assessment_id" IS NULL AND "evidence_artifacts"."environment" IS NULL AND "evidence_artifacts"."assessment_period" IS NOT NULL AND "evidence_artifacts"."status" NOT IN ('expired', 'purged');--> statement-breakpoint
CREATE UNIQUE INDEX `idx_evidence_dedupe_aen` ON `evidence_artifacts` (`sha256`,`source`,`control_id`,`framework`,`system`,`assessment_id`,`environment`) WHERE "evidence_artifacts"."assessment_id" IS NOT NULL AND "evidence_artifacts"."environment" IS NOT NULL AND "evidence_artifacts"."assessment_period" IS NULL AND "evidence_artifacts"."status" NOT IN ('expired', 'purged');--> statement-breakpoint
CREATE UNIQUE INDEX `idx_evidence_dedupe_anp` ON `evidence_artifacts` (`sha256`,`source`,`control_id`,`framework`,`system`,`assessment_id`,`assessment_period`) WHERE "evidence_artifacts"."assessment_id" IS NOT NULL AND "evidence_artifacts"."environment" IS NULL AND "evidence_artifacts"."assessment_period" IS NOT NULL AND "evidence_artifacts"."status" NOT IN ('expired', 'purged');--> statement-breakpoint
CREATE UNIQUE INDEX `idx_evidence_dedupe_nep` ON `evidence_artifacts` (`sha256`,`source`,`control_id`,`framework`,`system`,`environment`,`assessment_period`) WHERE "evidence_artifacts"."assessment_id" IS NULL AND "evidence_artifacts"."environment" IS NOT NULL AND "evidence_artifacts"."assessment_period" IS NOT NULL AND "evidence_artifacts"."status" NOT IN ('expired', 'purged');--> statement-breakpoint
CREATE UNIQUE INDEX `idx_evidence_dedupe_aep` ON `evidence_artifacts` (`sha256`,`source`,`control_id`,`framework`,`system`,`assessment_id`,`environment`,`assessment_period`) WHERE "evidence_artifacts"."assessment_id" IS NOT NULL AND "evidence_artifacts"."environment" IS NOT NULL AND "evidence_artifacts"."assessment_period" IS NOT NULL AND "evidence_artifacts"."status" NOT IN ('expired', 'purged');