@preconcurrency import AppKit

@MainActor
final class HelpController: NSObject, NSWindowDelegate {
    private var window: NSWindow?

    func show(outputDirectory: URL) {
        if let window { window.makeKeyAndOrderFront(nil); NSApplication.shared.activate(ignoringOtherApps: true); return }
        let frame = NSRect(x: 0, y: 0, width: 720, height: 660)
        let window = NSWindow(contentRect: frame, styleMask: [.titled, .closable, .resizable], backing: .buffered, defer: false)
        window.title = "Scopeproof Capture Help"
        window.center()
        window.delegate = self
        let scroll = NSScrollView(frame: frame)
        scroll.hasVerticalScroller = true
        scroll.autoresizingMask = [.width, .height]
        let text = NSTextView(frame: frame.insetBy(dx: 28, dy: 24))
        text.isEditable = false
        text.isSelectable = true
        text.drawsBackground = false
        text.textContainerInset = NSSize(width: 26, height: 24)
        text.textStorage?.setAttributedString(helpText(outputDirectory: outputDirectory))
        scroll.documentView = text
        window.contentView = scroll
        window.makeKeyAndOrderFront(nil)
        NSApplication.shared.activate(ignoringOtherApps: true)
        self.window = window
    }

    func windowWillClose(_ notification: Notification) { window = nil }

    private func helpText(outputDirectory: URL) -> NSAttributedString {
        let body = NSMutableAttributedString()
        func add(_ value: String, size: CGFloat, weight: NSFont.Weight = .regular, color: NSColor = .labelColor, spacing: CGFloat = 10) {
            let paragraph = NSMutableParagraphStyle(); paragraph.paragraphSpacing = spacing; paragraph.lineSpacing = 3
            body.append(NSAttributedString(string: value, attributes: [.font: NSFont.systemFont(ofSize: size, weight: weight), .foregroundColor: color, .paragraphStyle: paragraph]))
        }
        add("Scopeproof Capture\n", size: 28, weight: .bold, color: .systemIndigo, spacing: 4)
        add("Secure multi-framework compliance evidence from the macOS menu bar\n\n", size: 15, weight: .medium, color: .secondaryLabelColor)
        add("Local Console\n", size: 19, weight: .semibold)
        add("Choose Open Local Console from the shield menu. Scopeproof starts a private loopback-only console, opens it in your browser, and creates a short-lived authenticated session for this app launch. The console searches the local evidence folder, displays verified previews, records lifecycle decisions, and maintains a disposable SQLite index with an immutable HMAC-authenticated local audit chain. It never accepts filesystem paths from the browser. No hosted login or device-enrollment token is required for local capture, review, search, or assessor-package export.\n\n", size: 14)
        add("Quick start\n", size: 19, weight: .semibold)
        add("1. Open the evidence page, then choose Capture Frontmost Browser Window, Choose Browser Window, Capture Scrolling Evidence, Open URL & Capture, or Capture Entire Display.\n2. Before every screenshot, select PCI DSS, HIPAA, FedRAMP, SOC 2, ISO 27001, an imported catalog, or Custom, then select the corresponding control. Use Capture Presets for recurring collections.\n3. Customize the filename and add the evidence title, owner, system, environment, assessment period, optional Jira issue, tags, expected evidence, assessor note, and full Page URL. Capture Frontmost detects the active Safari, Chrome, Edge, or Arc tab when browser Automation access is available; Open URL & Capture supplies its target. Always confirm the detected address or paste it manually.\n4. Scopeproof removes URL credentials, redacts sensitive query/fragment values, prints the complete sanitized URL on a dedicated wrapping header line, and records it in the immutable manifest.\n5. Scopeproof keeps source pixels in memory, uses local OCR to find PANs, credentials, tokens, and private-key markers, adds the evidence header, and scans that composite again.\n6. In Review Evidence, drag across any additional sensitive value. Scopeproof then encodes and scans those exact final PNG pixels. A failed or incomplete scan saves nothing; no unreviewed PNG is written to disk.\n7. If connected, Scopeproof uploads the reviewed files into encrypted storage and returns a signed server-time receipt.\n\n", size: 14)
        add("Scrolling evidence\n", size: 19, weight: .semibold)
        add("Use Capture Scrolling Evidence when a page needs two or more screenshots. Select the exact browser window, let Scopeproof capture its current viewport, switch back to the browser, scroll down with a small visible overlap, return, and choose Capture Next Section. After at least two sections, choose Finish & Review. Keep the window size and browser zoom unchanged. Scopeproof creates one vertical image with numbered CONTINUED dividers and one timestamp/control/full-URL banner. Intermediate viewports remain only in memory; cancel, resize, capture, scan, or review failure saves nothing. The app limits section count and image dimensions so the final artifact remains safe to validate and upload.\n\n", size: 14)
        add("Generate a one-time repository SBOM\n", size: 19, weight: .semibold)
        add("Choose Generate Repository SBOM from the shield menu. Enter an exact https://github.com/owner/repository URL, a short-lived token selected only for that repository with Metadata: read and Contents: read, a branch/tag/commit, and CycloneDX 1.6 or SPDX 2.3. Scopeproof resolves the ref to an immutable commit and reads only recognized lockfile blobs through GitHub’s API. It never clones, builds, installs, executes, or unpacks repository content. Save the JSON and adjacent SHA-256 checksum, then revoke the token. The masked token is cleared at submission and is not written to settings, Keychain, evidence, audit data, logs, cookies, caches, or a retry queue. This direct local export is not automatically added to a hosted assessment; use the hosted SBOM workflow when assessment scoping, team review, approval, comparison, and assessor-package inclusion are required.\n\n", size: 14)
        add("Store evidence in AWS S3\n", size: 19, weight: .semibold)
        add("Choose AWS S3 Storage from the shield menu. Production compliance mode requires a nonempty prefix, an expiring STS session, customer-managed KMS encryption, Object Lock retention, Block Public Access, versioning, bucket-owner-enforced ownership, and a TLS/KMS bucket policy. Select SSE-KMS or DSSE-KMS when entering a KMS ARN; SSE-S3 does not use one. Save & Verify checks the AWS caller and effective posture. Create & Harden Bucket applies these controls only after an irreversible-retention warning; remove management permissions afterward. Compatible S3 can use a dedicated no-console, bucket/prefix-scoped IAM user only as a migration exception. Optional settings add FIPS endpoints, Deep Archive, replication, and version-aware browsing. Browse S3 Evidence lists up to 5,000 immutable versions and downloads only a selected PNG/JSON version after version-ID, ETag, size, checksum, and content validation. Downloads are private and quarantined. Credentials and the verified account/destination binding stay in separate device-only Keychain items. Upload receipts record exact S3 versions, checksums, KMS/retention posture, principal, and request IDs without credentials.\n\n", size: 14)
        add("What gets created\n", size: 19, weight: .semibold)
        add("Each browser capture produces a PNG with a live right-side Mac menu-bar pixel strip, a full-width evidence header, and the captured browser pixels, plus an adjacent immutable JSON manifest. Full-display evidence includes the real menu bar directly. The header contains the canonical timestamp, local clock/timezone reading, evidence ID, compliance framework, control number and title, optional Jira issue, system, assessment period, source window, and complete sanitized Page URL. Because the wrapping header is outside the original image, it never obscures evidence or truncates the URL. The manifest records the same timestamp and source URL plus SHA-256 integrity, catalog version, owner, tags, expected evidence, Jira reference, control mappings, automated/manual redaction counts, session metadata, and capture-chain links. Review state is derived only from the final verified .review.json lifecycle event, which binds reviewer, timestamp, artifact digest, rationale, and policy. Inconsistent or obsolete histories cannot be exported. Hosted uploads add a .receipt.json file; successful S3 pairs add a credential-free .s3.json receipt.\n\n", size: 14)
        add("Where files are stored\n", size: 19, weight: .semibold)
        add("\(outputDirectory.path)\nNew files are organized as Compliance area / Control / Assessment period. Filenames include the framework, control, your custom name, capture time, and evidence ID. Files are private to your macOS account. Use Open Evidence Folder from the menu. The configured retention action moves expired local evidence to Trash; it never deletes hosted evidence.\n\n", size: 14)
        add("Finding an earlier screenshot\n", size: 19, weight: .semibold)
        add("Choose Search Evidence from the shield menu. Filter by compliance area, control, review status, capture age, system, owner, tags, or keywords. Thumbnails make visual confirmation faster. Select Review Status to assign an owner and reviewer, record a rationale, add tags, and move evidence through Draft, In Review, Approved, Rejected, or Superseded. Approval, rejection, and supersession require a note. Search includes legacy root-level captures and every nested framework folder.\n\n", size: 14)
        add("Attaching evidence to Jira\n", size: 19, weight: .semibold)
        add("1. In the Scopeproof web console, open Connections → Jira Cloud. Enter the Jira Cloud site and approved project keys, continue to Atlassian OAuth, and test the connection. OAuth tokens remain encrypted on the hosted service and never enter this Mac app.\n2. Open Capture & Jira Settings on the Mac to set routing defaults, then enter the destination issue key (for example, GRC-123) while classifying a capture.\n3. Review the evidence and mark it Approved with a rationale. Upload those exact bytes to Scopeproof and have an authenticated web reviewer approve the hosted artifact.\n4. In Search Evidence, select the item and choose Upload to Jira Cloud. Scopeproof retrieves the live issue summary for confirmation, then verifies both approvals, the PNG digest, safety state, lifecycle chain, site, project allowlist, and Jira permissions before attaching the complete evidence set. A signed .jira.json receipt is saved beside the evidence.\n5. Copy Jira Comment and manual attachment remain available as a fallback. Confirm project permissions, external-auditor access, classification, and retention before any disclosure. Never attach an unredacted image, password, cookie, token, private key, or PAN.\n\n", size: 14)
        add("Preparing an external assessor package\n", size: 19, weight: .semibold)
        add("1. Open Search Evidence and review each artifact. Confirm its scope, timestamp, redactions, system, control mapping, and what it proves.\n2. Mark only complete, current artifacts Approved. Mark replaced evidence Superseded; rejected or superseded files never enter a package.\n3. Choose Export Assessor Package from the shield menu. Filter by compliance area and assessment period, enter a package name and preparer, then choose a save location.\n4. Scopeproof re-hashes every artifact, derives approval from the verified review-event chain, and creates a ZIP organized by framework and control. The package includes a Read Me, control-coverage/gap report, evidence index, signed JSON manifest, verification guide, PNGs, capture manifests, review histories, and server receipts. A separate ZIP checksum is written beside it.\n5. Approve the Keychain user-presence prompt to use the device-bound package-signing identity. Transfer both the ZIP and checksum through your approved secure file-sharing channel, then confirm the signing-key fingerprint out of band. Do not email regulated evidence unless policy explicitly permits it.\n\n", size: 14)
        add("Control catalogs and mappings\n", size: 19, weight: .semibold)
        add("The classification form shows the selected catalog version, control count, and source. Choose Update Controls to validate and import a current Scopeproof JSON, OSCAL catalog JSON, or CSV control list from the framework publisher or your organization's approved GRC source. Imports are limited to 5 MB, reject duplicate control IDs, and retain a SHA-256 provenance digest. An imported catalog can replace a built-in selection with the same framework name for future captures; existing evidence retains its original catalog metadata. Built-in lists are curated capture aids and are not a warranty that licensed or publisher-controlled standards are current or complete. Curated cross-framework mappings are also aids—not a substitute for assessor judgment or an authoritative framework crosswalk.\n\n", size: 14)
        add("Connecting to the web application\n", size: 19, weight: .semibold)
        add("Hosted synchronization is optional. For team review or Jira Cloud delivery, open the hosted Scopeproof console, enroll a Mac capture device, and copy the one-time token into Capture & Jira Settings. The token is stored in your login Keychain, not preferences. Leave Server URL blank for local-only mode. Failed or offline uploads always remain local and can be retried later.\n\n", size: 14)
        add("Permissions and safety\n", size: 19, weight: .semibold)
        add("Screen Recording is required so Apple’s ScreenCaptureKit can read the selected pixels. Capture Frontmost can also request browser Automation access to read only the active tab address after an explicit capture action; deny it to use manual Page URL entry. Scopeproof never captures on a timer or without an explicit menu action. OCR happens locally. The app does not read browser passwords, cookies, or page source. Always inspect the detected URL and preview—automated detectors reduce risk but cannot guarantee that every sensitive value is found.\n\n", size: 14)
        add("Troubleshooting\n", size: 19, weight: .semibold)
        add("• Local Console unavailable: quit and reopen Scopeproof Capture; the loopback address and browser session are recreated at launch.\n• Permission unavailable: enable Scopeproof Capture in System Settings → Privacy & Security → Screen & System Audio Recording, then restart it.\n• Frontmost URL is blank: paste and confirm the Page URL manually, or allow Scopeproof Capture to control that browser under System Settings → Privacy & Security → Automation. Firefox requires manual entry.\n• Wrong window: use Choose Browser Window instead of frontmost capture.\n• Control is missing or outdated: choose Update Controls in the classification form and import a current approved catalog; confirm the displayed version, source, and control count before capture.\n• Repository SBOM authentication failed: create a fresh repository-scoped token with Metadata: read and Contents: read, confirm repository selection, and submit a new run; one-time credentials never retry.\n• Repository SBOM has no components: commit a supported pinned lockfile or use the hosted workflow after a reviewed parser addition.\n• S3 credentials expired: obtain a fresh IAM Identity Center or AssumeRole session, include its expiration, and run Save & Verify.\n• S3 says SSE-S3 does not use a KMS key: select SSE-KMS or DSSE-KMS, or clear the KMS ARN for an intentional SSE-S3 bucket.\n• S3 posture failed: grant the documented read-only verifier actions temporarily and correct every reported KMS, Object Lock, policy, ownership, versioning, lifecycle, or replication control.\n• S3 bucket setup failed: automatic upload remains off. Correct the specific setup permission and retry Create & Harden Bucket; Scopeproof never deletes the partial bucket.\n• S3 browser cannot list versions: grant prefix-scoped s3:ListBucketVersions. Exact downloads require s3:GetObjectVersion and kms:Decrypt.\n• S3 checksum mismatch: keep the local evidence unchanged and investigate CloudTrail and the S3 request IDs as an integrity incident.\n• Cannot export: at least one matching artifact must be Approved, and all included hashes and lifecycle chains must validate.\n• Hosted upload unavailable: verify the server URL and replace a revoked or expired device token in Settings.\n• Jira Cloud upload unavailable: connect or reauthorize Jira under Scopeproof web → Connections, test it, and confirm the issue project is allowlisted.\n• No menu icon: open Scopeproof Capture from your Applications folder.\n• Update available: Check for Updates verifies release metadata; production releases can be Developer ID signed and notarized by the release script when credentials are configured.\n", size: 14)
        return body
    }
}
