import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull(),
  displayName: text("display_name").notNull(),
  role: text("role", { enum: ["admin", "compliance_lead", "reviewer", "auditor"] }).notNull().default("auditor"),
  status: text("status", { enum: ["active", "suspended", "revoked"] }).notNull().default("active"),
  invitedBy: text("invited_by"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  lastSeenAt: text("last_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("idx_users_email").on(table.email)]);

export const userInvitations = sqliteTable("user_invitations", {
  id: text("id").primaryKey(),
  email: text("email").notNull(),
  role: text("role", { enum: ["admin", "compliance_lead", "reviewer", "auditor"] }).notNull().default("auditor"),
  status: text("status", { enum: ["pending", "accepted", "revoked", "expired"] }).notNull().default("pending"),
  invitedBy: text("invited_by").notNull(),
  expiresAt: text("expires_at").notNull(),
  acceptedUserId: text("accepted_user_id"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  acceptedAt: text("accepted_at"),
  revokedAt: text("revoked_at"),
}, (table) => [
  uniqueIndex("idx_user_invitations_email_pending").on(table.email).where(sql`${table.status} = 'pending'`),
  index("idx_user_invitations_status_expiry").on(table.status, table.expiresAt),
]);

export const securityInvariants = sqliteTable("security_invariants", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const controlCatalogs = sqliteTable("control_catalogs", {
  id: text("id").primaryKey(),
  framework: text("framework").notNull(),
  version: text("version").notNull(),
  title: text("title").notNull(),
  controlsJson: text("controls_json").notNull(),
  digestSha256: text("digest_sha256").notNull(),
  status: text("status", { enum: ["active", "retired"] }).notNull().default("active"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("idx_control_catalog_framework_version").on(table.framework, table.version),
  uniqueIndex("idx_control_catalog_digest").on(table.digestSha256),
]);

export const assessments = sqliteTable("assessments", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  framework: text("framework").notNull(),
  periodStart: text("period_start").notNull(),
  periodEnd: text("period_end").notNull(),
  systemsJson: text("systems_json").notNull().default("[]"),
  controlsJson: text("controls_json").notNull().default("[]"),
  catalogId: text("catalog_id"),
  scopeMode: text("scope_mode", { enum: ["explicit"] }).notNull().default("explicit"),
  ownerId: text("owner_id").notNull(),
  status: text("status", { enum: ["draft", "active", "closed"] }).notNull().default("draft"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_assessments_status_period").on(table.status, table.periodEnd), index("idx_assessments_owner").on(table.ownerId)]);

export const captureDevices = sqliteTable("capture_devices", {
  id: text("id").primaryKey(),
  displayName: text("display_name").notNull(),
  platform: text("platform").notNull().default("macOS"),
  tokenHash: text("token_hash").notNull(),
  ownerId: text("owner_id").notNull(),
  status: text("status", { enum: ["active", "revoked"] }).notNull().default("active"),
  appVersion: text("app_version"),
  lastSeenAt: text("last_seen_at"),
  tokenIssuedAt: text("token_issued_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  tokenExpiresAt: text("token_expires_at").notNull().default(sql`datetime('now', '+30 days')`),
  tokenLastRotatedAt: text("token_last_rotated_at"),
  provenanceKeyId: text("provenance_key_id"),
  provenancePublicKey: text("provenance_public_key"),
  chainSequence: integer("chain_sequence").notNull().default(0),
  chainEventHash: text("chain_event_hash").notNull().default("GENESIS"),
  chainPendingLeaseId: text("chain_pending_lease_id"),
  chainPendingSequence: integer("chain_pending_sequence"),
  chainPendingPreviousHash: text("chain_pending_previous_hash"),
  chainPendingEventHash: text("chain_pending_event_hash"),
  chainPendingEvidenceId: text("chain_pending_evidence_id"),
  chainPendingExpiresAt: text("chain_pending_expires_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  revokedAt: text("revoked_at"),
}, (table) => [
  uniqueIndex("idx_capture_devices_token_hash").on(table.tokenHash),
  uniqueIndex("idx_capture_devices_provenance_key").on(table.provenanceKeyId),
  index("idx_capture_devices_owner_status").on(table.ownerId, table.status),
]);

export const captureSessions = sqliteTable("capture_sessions", {
  id: text("id").primaryKey(),
  displayName: text("display_name").notNull(),
  controlId: text("control_id").notNull(),
  system: text("system_name").notNull(),
  environment: text("environment").notNull(),
  assessmentPeriod: text("assessment_period").notNull(),
  createdBy: text("created_by").notNull(),
  status: text("status", { enum: ["open", "complete"] }).notNull().default("open"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text("completed_at"),
}, (table) => [index("idx_capture_sessions_control_created").on(table.controlId, table.createdAt), index("idx_capture_sessions_creator_status").on(table.createdBy, table.status)]);

export const collectors = sqliteTable("collectors", {
  id: text("id").primaryKey(),
  provider: text("provider", { enum: ["aws", "github", "okta", "cloudflare", "browser"] }).notNull(),
  displayName: text("display_name").notNull(),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  configJson: text("config_json").notNull().default("{}"),
  scheduleCron: text("schedule_cron"),
  status: text("status", { enum: ["not_configured", "healthy", "action_needed", "running"] }).notNull().default("not_configured"),
  lastRunAt: text("last_run_at"),
  lastError: text("last_error"),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_collectors_provider").on(table.provider), index("idx_collectors_enabled").on(table.enabled)]);

export const collectionJobs = sqliteTable("collection_jobs", {
  id: text("id").primaryKey(),
  collectorId: text("collector_id").notNull(),
  requestedBy: text("requested_by").notNull(),
  triggerType: text("trigger_type", { enum: ["manual", "scheduled", "retry"] }).notNull(),
  status: text("status", { enum: ["queued", "running", "completed", "partial", "retrying", "failed"] }).notNull().default("queued"),
  attempt: integer("attempt").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(3),
  artifactCount: integer("artifact_count").notNull().default(0),
  nextAttemptAt: text("next_attempt_at"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  startedAt: text("started_at"),
  completedAt: text("completed_at"),
  leaseId: text("lease_id"),
  leaseExpiresAt: text("lease_expires_at"),
  assessmentId: text("assessment_id"),
  coverageStatus: text("coverage_status", { enum: ["complete", "partial", "unknown"] }).notNull().default("unknown"),
  coverageJson: text("coverage_json").notNull().default("{}"),
}, (table) => [index("idx_jobs_status_next_attempt").on(table.status, table.nextAttemptAt), index("idx_jobs_collector_created").on(table.collectorId, table.createdAt)]);

export const sbomJobs = sqliteTable("sbom_jobs", {
  id: text("id").primaryKey(),
  requestedBy: text("requested_by").notNull(),
  assessmentId: text("assessment_id").notNull(),
  repositoryOwner: text("repository_owner").notNull(),
  repositoryName: text("repository_name").notNull(),
  repositoryFullName: text("repository_full_name").notNull(),
  requestedRef: text("requested_ref").notNull(),
  resolvedCommitSha: text("resolved_commit_sha"),
  format: text("format", { enum: ["cyclonedx_json", "spdx_json"] }).notNull(),
  status: text("status", { enum: ["queued", "running", "completed", "retrying", "failed"] }).notNull().default("queued"),
  attempt: integer("attempt").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(3),
  nextAttemptAt: text("next_attempt_at"),
  leaseId: text("lease_id"),
  leaseExpiresAt: text("lease_expires_at"),
  evidenceId: text("evidence_id"),
  previousJobId: text("previous_job_id"),
  componentCount: integer("component_count").notNull().default(0),
  directDependencyCount: integer("direct_dependency_count").notNull().default(0),
  manifestCount: integer("manifest_count").notNull().default(0),
  sourceArchiveSha256: text("source_archive_sha256"),
  artifactSha256: text("artifact_sha256"),
  generatorName: text("generator_name").notNull().default("scopeproof-static-sbom"),
  generatorVersion: text("generator_version").notNull().default("1.0.0"),
  manifestsJson: text("manifests_json").notNull().default("[]"),
  componentsJson: text("components_json").notNull().default("[]"),
  comparisonJson: text("comparison_json").notNull().default("{}"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  startedAt: text("started_at"),
  completedAt: text("completed_at"),
}, (table) => [
  index("idx_sbom_jobs_assessment_created").on(table.assessmentId, table.createdAt),
  index("idx_sbom_jobs_status_next_attempt").on(table.status, table.nextAttemptAt),
  index("idx_sbom_jobs_repo_completed").on(table.repositoryFullName, table.completedAt),
  index("idx_sbom_jobs_evidence").on(table.evidenceId),
]);

export const evidenceArtifacts = sqliteTable("evidence_artifacts", {
  id: text("id").primaryKey(),
  controlId: text("control_id").notNull(),
  framework: text("framework").notNull().default("PCI DSS 4.0.1"),
  catalogVersion: text("catalog_version"),
  title: text("title").notNull(),
  description: text("description").notNull().default(""),
  type: text("type", { enum: ["screenshot", "code", "configuration", "report"] }).notNull(),
  source: text("source").notNull(),
  system: text("system").notNull(),
  environment: text("environment"),
  assessmentPeriod: text("assessment_period"),
  evidenceOwner: text("evidence_owner"),
  tagsJson: text("tags_json").notNull().default("[]"),
  expectedEvidence: text("expected_evidence"),
  mappedControlsJson: text("mapped_controls_json").notNull().default("[]"),
  jiraIssueKey: text("jira_issue_key"),
  jiraIssueURL: text("jira_issue_url"),
  collectorId: text("collector_id"),
  jobId: text("job_id"),
  sessionId: text("session_id"),
  deviceId: text("device_id"),
  r2Key: text("r2_key").notNull(),
  contentType: text("content_type").notNull(),
  byteSize: integer("byte_size").notNull(),
  sha256: text("sha256").notNull(),
  encryptionIv: text("encryption_iv").notNull(),
  encryptionVersion: integer("encryption_version").notNull().default(1),
  encryptionKeyId: text("encryption_key_id").notNull().default("legacy-v1"),
  capturedAt: text("captured_at").notNull(),
  expiresAt: text("expires_at").notNull(),
  status: text("status", { enum: ["needs_review", "approved", "expiring", "rejected", "returned", "superseded", "expired", "purged"] }).notNull().default("needs_review"),
  redactionCount: integer("redaction_count").notNull().default(0),
  manualRedactions: integer("manual_redactions").notNull().default(0),
  redactionSummaryJson: text("redaction_summary_json").notNull().default("[]"),
  manifestSha256: text("manifest_sha256"),
  chainPreviousHash: text("chain_previous_hash"),
  chainEventHash: text("chain_event_hash"),
  timestampAuthority: text("timestamp_authority"),
  timestampToken: text("timestamp_token"),
  safetyScanSha256: text("safety_scan_sha256"),
  safetyScanPolicy: text("safety_scan_policy"),
  safetyScanCompletedAt: text("safety_scan_completed_at"),
  serverSafetyScanSha256: text("server_safety_scan_sha256"),
  serverSafetyScanPolicy: text("server_safety_scan_policy"),
  serverSafetyScanCompletedAt: text("server_safety_scan_completed_at"),
  serverSafetyScannerOrigin: text("server_safety_scanner_origin"),
  serverSafetyReceiptSha256: text("server_safety_receipt_sha256"),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  approvedBy: text("approved_by"),
  approvedAt: text("approved_at"),
  purgedAt: text("purged_at"),
  purgeAttempts: integer("purge_attempts").notNull().default(0),
  purgeError: text("purge_error"),
  rotationLeaseId: text("rotation_lease_id"),
  rotationLeaseExpiresAt: text("rotation_lease_expires_at"),
  rotationPendingR2Key: text("rotation_pending_r2_key"),
  rotationPreviousR2Key: text("rotation_previous_r2_key"),
  assessmentId: text("assessment_id"),
  coverageStatus: text("coverage_status", { enum: ["complete", "partial", "not_applicable"] }).notNull().default("not_applicable"),
  coverageJson: text("coverage_json").notNull().default("{}"),
}, (table) => [
  uniqueIndex("idx_evidence_dedupe_nnn").on(table.sha256, table.source, table.controlId, table.framework, table.system)
    .where(sql`${table.assessmentId} IS NULL AND ${table.environment} IS NULL AND ${table.assessmentPeriod} IS NULL AND ${table.status} NOT IN ('expired', 'purged')`),
  uniqueIndex("idx_evidence_dedupe_ann").on(table.sha256, table.source, table.controlId, table.framework, table.system, table.assessmentId)
    .where(sql`${table.assessmentId} IS NOT NULL AND ${table.environment} IS NULL AND ${table.assessmentPeriod} IS NULL AND ${table.status} NOT IN ('expired', 'purged')`),
  uniqueIndex("idx_evidence_dedupe_nen").on(table.sha256, table.source, table.controlId, table.framework, table.system, table.environment)
    .where(sql`${table.assessmentId} IS NULL AND ${table.environment} IS NOT NULL AND ${table.assessmentPeriod} IS NULL AND ${table.status} NOT IN ('expired', 'purged')`),
  uniqueIndex("idx_evidence_dedupe_nnp").on(table.sha256, table.source, table.controlId, table.framework, table.system, table.assessmentPeriod)
    .where(sql`${table.assessmentId} IS NULL AND ${table.environment} IS NULL AND ${table.assessmentPeriod} IS NOT NULL AND ${table.status} NOT IN ('expired', 'purged')`),
  uniqueIndex("idx_evidence_dedupe_aen").on(table.sha256, table.source, table.controlId, table.framework, table.system, table.assessmentId, table.environment)
    .where(sql`${table.assessmentId} IS NOT NULL AND ${table.environment} IS NOT NULL AND ${table.assessmentPeriod} IS NULL AND ${table.status} NOT IN ('expired', 'purged')`),
  uniqueIndex("idx_evidence_dedupe_anp").on(table.sha256, table.source, table.controlId, table.framework, table.system, table.assessmentId, table.assessmentPeriod)
    .where(sql`${table.assessmentId} IS NOT NULL AND ${table.environment} IS NULL AND ${table.assessmentPeriod} IS NOT NULL AND ${table.status} NOT IN ('expired', 'purged')`),
  uniqueIndex("idx_evidence_dedupe_nep").on(table.sha256, table.source, table.controlId, table.framework, table.system, table.environment, table.assessmentPeriod)
    .where(sql`${table.assessmentId} IS NULL AND ${table.environment} IS NOT NULL AND ${table.assessmentPeriod} IS NOT NULL AND ${table.status} NOT IN ('expired', 'purged')`),
  uniqueIndex("idx_evidence_dedupe_aep").on(table.sha256, table.source, table.controlId, table.framework, table.system, table.assessmentId, table.environment, table.assessmentPeriod)
    .where(sql`${table.assessmentId} IS NOT NULL AND ${table.environment} IS NOT NULL AND ${table.assessmentPeriod} IS NOT NULL AND ${table.status} NOT IN ('expired', 'purged')`),
  index("idx_evidence_status_created").on(table.status, table.createdAt),
  index("idx_evidence_control_captured").on(table.controlId, table.capturedAt),
  index("idx_evidence_framework_control").on(table.framework, table.controlId),
  index("idx_evidence_job").on(table.jobId),
  index("idx_evidence_device_captured").on(table.deviceId, table.capturedAt),
  index("idx_evidence_session").on(table.sessionId),
  index("idx_evidence_jira_issue").on(table.jiraIssueKey),
  index("idx_evidence_assessment_status").on(table.assessmentId, table.status),
]);

export const evidenceOccurrences = sqliteTable("evidence_occurrences", {
  id: text("id").primaryKey(),
  artifactId: text("artifact_id").notNull(),
  jobId: text("job_id"),
  sessionId: text("session_id"),
  deviceId: text("device_id"),
  capturedAt: text("captured_at").notNull(),
  receivedAt: text("received_at").notNull(),
  createdBy: text("created_by").notNull(),
  expiresAt: text("expires_at").notNull(),
  status: text("status", { enum: ["needs_review", "approved", "rejected", "returned", "superseded", "expired"] }).notNull().default("needs_review"),
  coverageStatus: text("coverage_status", { enum: ["complete", "partial", "not_applicable"] }).notNull().default("not_applicable"),
  coverageJson: text("coverage_json").notNull().default("{}"),
  approvedBy: text("approved_by"),
  approvedAt: text("approved_at"),
  lastReviewEventId: text("last_review_event_id"),
  provenanceJson: text("provenance_json").notNull().default("{}"),
}, (table) => [
  uniqueIndex("idx_evidence_occurrences_job_artifact").on(table.jobId, table.artifactId),
  index("idx_evidence_occurrences_artifact_received").on(table.artifactId, table.receivedAt),
  index("idx_evidence_occurrences_device_captured").on(table.deviceId, table.capturedAt),
]);

export const evidenceReviewEvents = sqliteTable("evidence_review_events", {
  id: text("id").primaryKey(),
  evidenceId: text("evidence_id").notNull(),
  occurrenceId: text("occurrence_id").notNull(),
  action: text("action", { enum: ["approved", "rejected", "returned", "reopened", "superseded"] }).notNull(),
  previousStatus: text("previous_status").notNull(),
  resultingStatus: text("resulting_status").notNull(),
  rationale: text("rationale").notNull(),
  expectedSha256: text("expected_sha256").notNull(),
  replacementEvidenceId: text("replacement_evidence_id"),
  actorId: text("actor_id").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  index("idx_review_events_evidence_created").on(table.evidenceId, table.createdAt),
  index("idx_review_events_actor_created").on(table.actorId, table.createdAt),
]);

export const findings = sqliteTable("findings", {
  id: text("id").primaryKey(),
  assessmentId: text("assessment_id").notNull(),
  controlId: text("control_id"),
  evidenceId: text("evidence_id"),
  jobId: text("job_id"),
  title: text("title").notNull(),
  description: text("description").notNull(),
  severity: text("severity", { enum: ["critical", "high", "medium", "low"] }).notNull(),
  status: text("status", { enum: ["open", "in_progress", "accepted", "resolved", "closed"] }).notNull().default("open"),
  ownerId: text("owner_id"),
  dueAt: text("due_at"),
  resolution: text("resolution"),
  createdBy: text("created_by").notNull(),
  resolvedBy: text("resolved_by"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  resolvedAt: text("resolved_at"),
}, (table) => [
  index("idx_findings_assessment_status_created").on(table.assessmentId, table.status, table.createdAt),
  index("idx_findings_owner_status").on(table.ownerId, table.status),
  index("idx_findings_evidence").on(table.evidenceId),
]);

export const findingEvents = sqliteTable("finding_events", {
  id: text("id").primaryKey(),
  findingId: text("finding_id").notNull(),
  action: text("action").notNull(),
  actorId: text("actor_id").notNull(),
  detailsJson: text("details_json").notNull().default("{}"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_finding_events_finding_created").on(table.findingId, table.createdAt)]);

export const retentionHolds = sqliteTable("retention_holds", {
  evidenceId: text("evidence_id").primaryKey(),
  ownerId: text("owner_id").notNull(),
  reason: text("reason").notNull(),
  expiresAt: text("expires_at").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_retention_holds_expiry").on(table.expiresAt)]);

export const retentionHoldReleaseRequests = sqliteTable("retention_hold_release_requests", {
  id: text("id").primaryKey(),
  evidenceId: text("evidence_id").notNull(),
  requestedBy: text("requested_by").notNull(),
  reason: text("reason").notNull(),
  requestDigest: text("request_digest").notNull(),
  holdOwnerId: text("hold_owner_id").notNull(),
  holdReason: text("hold_reason").notNull(),
  holdExpiresAt: text("hold_expires_at").notNull(),
  status: text("status", { enum: ["pending", "approved", "cancelled", "expired"] }).notNull().default("pending"),
  requestedAt: text("requested_at").notNull(),
  expiresAt: text("expires_at").notNull(),
  approvedBy: text("approved_by"),
  approvedAt: text("approved_at"),
  releasedAt: text("released_at"),
}, (table) => [
  uniqueIndex("idx_hold_release_pending_evidence").on(table.evidenceId).where(sql`${table.status} = 'pending'`),
  uniqueIndex("idx_hold_release_digest").on(table.requestDigest),
  index("idx_hold_release_status_expiry").on(table.status, table.expiresAt),
]);

export const rateLimitBuckets = sqliteTable("rate_limit_buckets", {
  keyHash: text("key_hash").primaryKey(),
  windowStart: integer("window_start").notNull(),
  requestCount: integer("request_count").notNull().default(0),
  expiresAt: integer("expires_at").notNull(),
}, (table) => [index("idx_rate_limit_expiry").on(table.expiresAt)]);

export const nativeEvidenceManifests = sqliteTable("native_evidence_manifests", {
  id: text("id").primaryKey(),
  deviceId: text("device_id").notNull(),
  localEvidenceId: text("local_evidence_id").notNull(),
  artifactId: text("artifact_id").notNull(),
  manifestSha256: text("manifest_sha256").notNull(),
  imageSha256: text("image_sha256").notNull(),
  jiraIssueKey: text("jira_issue_key"),
  chainSequence: integer("chain_sequence"),
  chainEventHash: text("chain_event_hash"),
  provenanceKeyId: text("provenance_key_id"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("idx_native_manifest_device_local").on(table.deviceId, table.localEvidenceId),
  uniqueIndex("idx_native_manifest_device_sequence").on(table.deviceId, table.chainSequence),
  index("idx_native_manifest_artifact").on(table.artifactId),
]);

export const auditEvents = sqliteTable("audit_events", {
  sequence: integer("sequence").primaryKey({ autoIncrement: true }),
  id: text("id").notNull(),
  occurredAt: text("occurred_at").notNull(),
  actorId: text("actor_id").notNull(),
  actorEmail: text("actor_email").notNull(),
  action: text("action").notNull(),
  resourceType: text("resource_type").notNull(),
  resourceId: text("resource_id").notNull(),
  detailsJson: text("details_json").notNull().default("{}"),
  previousHash: text("previous_hash").notNull(),
  eventHash: text("event_hash").notNull(),
  signature: text("signature").notNull(),
  hmacKeyId: text("hmac_key_id").notNull().default("legacy-v1"),
}, (table) => [uniqueIndex("idx_audit_id").on(table.id), uniqueIndex("idx_audit_event_hash").on(table.eventHash), index("idx_audit_resource").on(table.resourceType, table.resourceId), index("idx_audit_occurred").on(table.occurredAt)]);

// Transient rows let executeAuditedBatch fail the whole SQLite batch when a
// compare-and-swap mutation changes data but its postcondition is not true.
// Successful requests delete their guard before commit, so this table should
// remain empty outside an in-flight transaction.
export const auditBatchGuards = sqliteTable("audit_batch_guards", {
  id: text("id").primaryKey(),
  baselineChanges: integer("baseline_changes").notNull(),
  mutationChanges: integer("mutation_changes").notNull().default(0),
  valid: integer("valid").notNull().default(1),
}, (table) => [check("audit_batch_guards_valid", sql`${table.valid} = 1`)]);

export const exportPackages = sqliteTable("export_packages", {
  id: text("id").primaryKey(),
  requestedBy: text("requested_by").notNull(),
  status: text("status", { enum: ["building", "ready", "failed"] }).notNull().default("building"),
  r2Key: text("r2_key"),
  sha256: text("sha256"),
  signature: text("signature"),
  evidenceCount: integer("evidence_count").notNull().default(0),
  byteSize: integer("byte_size").notNull().default(0),
  errorMessage: text("error_message"),
  rotationLeaseId: text("rotation_lease_id"),
  rotationLeaseExpiresAt: text("rotation_lease_expires_at"),
  rotationPendingR2Key: text("rotation_pending_r2_key"),
  rotationPreviousR2Key: text("rotation_previous_r2_key"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text("completed_at"),
  expiresAt: text("expires_at"),
  assessmentId: text("assessment_id"),
  selectionJson: text("selection_json").notNull().default("{}"),
  excludedCount: integer("excluded_count").notNull().default(0),
  encryptionKeyId: text("encryption_key_id").notNull().default("legacy-v1"),
}, (table) => [index("idx_exports_requested_created").on(table.requestedBy, table.createdAt), index("idx_exports_assessment_created").on(table.assessmentId, table.createdAt)]);

export const jiraConnections = sqliteTable("jira_connections", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  cloudId: text("cloud_id").notNull(),
  siteUrl: text("site_url").notNull(),
  siteName: text("site_name").notNull(),
  allowedProjectsJson: text("allowed_projects_json").notNull().default("[]"),
  accessTokenCiphertext: text("access_token_ciphertext").notNull(),
  accessTokenIv: text("access_token_iv").notNull(),
  refreshTokenCiphertext: text("refresh_token_ciphertext").notNull(),
  refreshTokenIv: text("refresh_token_iv").notNull(),
  accessTokenExpiresAt: text("access_token_expires_at").notNull(),
  scopes: text("scopes").notNull(),
  status: text("status", { enum: ["active", "reauthorization_required"] }).notNull().default("active"),
  tokenVersion: integer("token_version").notNull().default(1),
  tokenKeyId: text("token_key_id").notNull().default("legacy-v1"),
  refreshLeaseId: text("refresh_lease_id"),
  refreshLeaseExpiresAt: text("refresh_lease_expires_at"),
  lastTestedAt: text("last_tested_at"),
  lastError: text("last_error"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("idx_jira_connections_user").on(table.userId), uniqueIndex("idx_jira_connections_user_cloud").on(table.userId, table.cloudId)]);

export const jiraOauthStates = sqliteTable("jira_oauth_states", {
  stateHash: text("state_hash").primaryKey(),
  userId: text("user_id").notNull(),
  requestedSiteUrl: text("requested_site_url").notNull(),
  allowedProjectsJson: text("allowed_projects_json").notNull(),
  expiresAt: text("expires_at").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_jira_oauth_states_user_expires").on(table.userId, table.expiresAt)]);

export const jiraUploadReceipts = sqliteTable("jira_upload_receipts", {
  id: text("id").primaryKey(),
  connectionId: text("connection_id").notNull(),
  userId: text("user_id").notNull(),
  deviceId: text("device_id").notNull(),
  evidenceId: text("evidence_id").notNull(),
  issueKey: text("issue_key").notNull(),
  siteUrl: text("site_url").notNull(),
  uploadedAt: text("uploaded_at").notNull(),
  attachmentsJson: text("attachments_json").notNull(),
  receiptSha256: text("receipt_sha256").notNull(),
  signature: text("signature").notNull(),
  hmacKeyId: text("hmac_key_id").notNull().default("legacy-v1"),
}, (table) => [
  uniqueIndex("idx_jira_upload_receipts_target").on(table.connectionId, table.evidenceId, table.issueKey),
  uniqueIndex("idx_jira_upload_receipts_sha").on(table.receiptSha256),
  index("idx_jira_upload_receipts_user_created").on(table.userId, table.uploadedAt),
]);

export const auditCheckpoints = sqliteTable("audit_checkpoints", {
  id: text("id").primaryKey(),
  sequence: integer("sequence").notNull(),
  eventHash: text("event_hash").notNull(),
  eventCount: integer("event_count").notNull(),
  hmacKeyId: text("hmac_key_id").notNull(),
  checkpointSha256: text("checkpoint_sha256").notNull(),
  signature: text("signature").notNull(),
  publicKeyFingerprint: text("public_key_fingerprint").notNull(),
  r2Key: text("r2_key").notNull(),
  externalStatus: text("external_status", { enum: ["delivered", "not_configured", "failed"] }).notNull(),
  externalReceipt: text("external_receipt"),
  externalReceiptSha256: text("external_receipt_sha256"),
  externalReceiptSignature: text("external_receipt_signature"),
  externalReceiptR2Key: text("external_receipt_r2_key"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("idx_audit_checkpoints_sequence").on(table.sequence), uniqueIndex("idx_audit_checkpoints_sha").on(table.checkpointSha256)]);

export const jiraUploadOperations = sqliteTable("jira_upload_operations", {
  id: text("id").primaryKey(),
  connectionId: text("connection_id").notNull(),
  userId: text("user_id").notNull(),
  deviceId: text("device_id").notNull(),
  evidenceId: text("evidence_id").notNull(),
  issueKey: text("issue_key").notNull(),
  requestSha256: text("request_sha256").notNull(),
  status: text("status", { enum: ["reserved", "uploading", "succeeded", "failed", "unknown"] }).notNull().default("reserved"),
  leaseId: text("lease_id"),
  leaseExpiresAt: text("lease_expires_at"),
  attempt: integer("attempt").notNull().default(0),
  receiptId: text("receipt_id"),
  lastError: text("last_error"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("idx_jira_upload_operations_target").on(table.connectionId, table.evidenceId, table.issueKey),
  index("idx_jira_upload_operations_status_lease").on(table.status, table.leaseExpiresAt),
]);
