import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull(),
  displayName: text("display_name").notNull(),
  role: text("role", { enum: ["admin", "compliance_lead", "reviewer", "auditor"] }).notNull().default("auditor"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  lastSeenAt: text("last_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("idx_users_email").on(table.email)]);

export const securityInvariants = sqliteTable("security_invariants", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const assessments = sqliteTable("assessments", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  framework: text("framework").notNull(),
  periodStart: text("period_start").notNull(),
  periodEnd: text("period_end").notNull(),
  systemsJson: text("systems_json").notNull().default("[]"),
  controlsJson: text("controls_json").notNull().default("[]"),
  ownerId: text("owner_id").notNull(),
  status: text("status", { enum: ["draft", "active", "closed"] }).notNull().default("draft"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_assessments_status_period").on(table.status, table.periodEnd), index("idx_assessments_owner").on(table.ownerId)]);

export const captureDevices = sqliteTable("capture_devices", {
  id: text("id").primaryKey(),
  displayName: text("display_name").notNull(),
  platform: text("platform").notNull().default("macOS"),
  tokenHash: text("token_hash").notNull(),
  ownerId: text("owner_id").notNull(),
  status: text("status", { enum: ["active", "revoked"] }).notNull().default("active"),
  appVersion: text("app_version"),
  lastSeenAt: text("last_seen_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  revokedAt: text("revoked_at"),
}, (table) => [uniqueIndex("idx_capture_devices_token_hash").on(table.tokenHash), index("idx_capture_devices_owner_status").on(table.ownerId, table.status)]);

export const captureSessions = sqliteTable("capture_sessions", {
  id: text("id").primaryKey(),
  displayName: text("display_name").notNull(),
  controlId: text("control_id").notNull(),
  system: text("system_name").notNull(),
  environment: text("environment").notNull(),
  assessmentPeriod: text("assessment_period").notNull(),
  createdBy: text("created_by").notNull(),
  status: text("status", { enum: ["open", "complete"] }).notNull().default("open"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text("completed_at"),
}, (table) => [index("idx_capture_sessions_control_created").on(table.controlId, table.createdAt), index("idx_capture_sessions_creator_status").on(table.createdBy, table.status)]);

export const collectors = sqliteTable("collectors", {
  id: text("id").primaryKey(),
  provider: text("provider", { enum: ["aws", "github", "okta", "cloudflare", "browser"] }).notNull(),
  displayName: text("display_name").notNull(),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  configJson: text("config_json").notNull().default("{}"),
  scheduleCron: text("schedule_cron"),
  status: text("status", { enum: ["not_configured", "healthy", "action_needed", "running"] }).notNull().default("not_configured"),
  lastRunAt: text("last_run_at"),
  lastError: text("last_error"),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_collectors_provider").on(table.provider), index("idx_collectors_enabled").on(table.enabled)]);

export const collectionJobs = sqliteTable("collection_jobs", {
  id: text("id").primaryKey(),
  collectorId: text("collector_id").notNull(),
  requestedBy: text("requested_by").notNull(),
  triggerType: text("trigger_type", { enum: ["manual", "scheduled", "retry"] }).notNull(),
  status: text("status", { enum: ["queued", "running", "completed", "partial", "retrying", "failed"] }).notNull().default("queued"),
  attempt: integer("attempt").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(3),
  artifactCount: integer("artifact_count").notNull().default(0),
  nextAttemptAt: text("next_attempt_at"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  startedAt: text("started_at"),
  completedAt: text("completed_at"),
  leaseId: text("lease_id"),
  leaseExpiresAt: text("lease_expires_at"),
  assessmentId: text("assessment_id"),
  coverageStatus: text("coverage_status", { enum: ["complete", "partial", "unknown"] }).notNull().default("unknown"),
  coverageJson: text("coverage_json").notNull().default("{}"),
}, (table) => [index("idx_jobs_status_next_attempt").on(table.status, table.nextAttemptAt), index("idx_jobs_collector_created").on(table.collectorId, table.createdAt)]);

export const evidenceArtifacts = sqliteTable("evidence_artifacts", {
  id: text("id").primaryKey(),
  controlId: text("control_id").notNull(),
  framework: text("framework").notNull().default("PCI DSS 4.0.1"),
  catalogVersion: text("catalog_version"),
  title: text("title").notNull(),
  description: text("description").notNull().default(""),
  type: text("type", { enum: ["screenshot", "code", "configuration", "report"] }).notNull(),
  source: text("source").notNull(),
  system: text("system").notNull(),
  environment: text("environment"),
  assessmentPeriod: text("assessment_period"),
  evidenceOwner: text("evidence_owner"),
  tagsJson: text("tags_json").notNull().default("[]"),
  expectedEvidence: text("expected_evidence"),
  mappedControlsJson: text("mapped_controls_json").notNull().default("[]"),
  jiraIssueKey: text("jira_issue_key"),
  jiraIssueURL: text("jira_issue_url"),
  collectorId: text("collector_id"),
  jobId: text("job_id"),
  sessionId: text("session_id"),
  deviceId: text("device_id"),
  r2Key: text("r2_key").notNull(),
  contentType: text("content_type").notNull(),
  byteSize: integer("byte_size").notNull(),
  sha256: text("sha256").notNull(),
  encryptionIv: text("encryption_iv").notNull(),
  encryptionVersion: integer("encryption_version").notNull().default(1),
  capturedAt: text("captured_at").notNull(),
  expiresAt: text("expires_at").notNull(),
  status: text("status", { enum: ["needs_review", "approved", "expiring", "rejected", "expired", "purged"] }).notNull().default("needs_review"),
  redactionCount: integer("redaction_count").notNull().default(0),
  manualRedactions: integer("manual_redactions").notNull().default(0),
  redactionSummaryJson: text("redaction_summary_json").notNull().default("[]"),
  manifestSha256: text("manifest_sha256"),
  chainPreviousHash: text("chain_previous_hash"),
  chainEventHash: text("chain_event_hash"),
  timestampAuthority: text("timestamp_authority"),
  timestampToken: text("timestamp_token"),
  safetyScanSha256: text("safety_scan_sha256"),
  safetyScanPolicy: text("safety_scan_policy"),
  safetyScanCompletedAt: text("safety_scan_completed_at"),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  approvedBy: text("approved_by"),
  approvedAt: text("approved_at"),
  purgedAt: text("purged_at"),
  purgeAttempts: integer("purge_attempts").notNull().default(0),
  purgeError: text("purge_error"),
  assessmentId: text("assessment_id"),
  coverageStatus: text("coverage_status", { enum: ["complete", "partial", "not_applicable"] }).notNull().default("not_applicable"),
  coverageJson: text("coverage_json").notNull().default("{}"),
}, (table) => [
  uniqueIndex("idx_evidence_sha_source_control").on(table.sha256, table.source, table.controlId),
  index("idx_evidence_status_created").on(table.status, table.createdAt),
  index("idx_evidence_control_captured").on(table.controlId, table.capturedAt),
  index("idx_evidence_framework_control").on(table.framework, table.controlId),
  index("idx_evidence_job").on(table.jobId),
  index("idx_evidence_device_captured").on(table.deviceId, table.capturedAt),
  index("idx_evidence_session").on(table.sessionId),
  index("idx_evidence_jira_issue").on(table.jiraIssueKey),
  index("idx_evidence_assessment_status").on(table.assessmentId, table.status),
]);

export const retentionHolds = sqliteTable("retention_holds", {
  evidenceId: text("evidence_id").primaryKey(),
  ownerId: text("owner_id").notNull(),
  reason: text("reason").notNull(),
  expiresAt: text("expires_at").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_retention_holds_expiry").on(table.expiresAt)]);

export const rateLimitBuckets = sqliteTable("rate_limit_buckets", {
  keyHash: text("key_hash").primaryKey(),
  windowStart: integer("window_start").notNull(),
  requestCount: integer("request_count").notNull().default(0),
  expiresAt: integer("expires_at").notNull(),
}, (table) => [index("idx_rate_limit_expiry").on(table.expiresAt)]);

export const nativeEvidenceManifests = sqliteTable("native_evidence_manifests", {
  id: text("id").primaryKey(),
  deviceId: text("device_id").notNull(),
  localEvidenceId: text("local_evidence_id").notNull(),
  artifactId: text("artifact_id").notNull(),
  manifestSha256: text("manifest_sha256").notNull(),
  imageSha256: text("image_sha256").notNull(),
  jiraIssueKey: text("jira_issue_key"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("idx_native_manifest_device_local").on(table.deviceId, table.localEvidenceId),
  index("idx_native_manifest_artifact").on(table.artifactId),
]);

export const auditEvents = sqliteTable("audit_events", {
  sequence: integer("sequence").primaryKey({ autoIncrement: true }),
  id: text("id").notNull(),
  occurredAt: text("occurred_at").notNull(),
  actorId: text("actor_id").notNull(),
  actorEmail: text("actor_email").notNull(),
  action: text("action").notNull(),
  resourceType: text("resource_type").notNull(),
  resourceId: text("resource_id").notNull(),
  detailsJson: text("details_json").notNull().default("{}"),
  previousHash: text("previous_hash").notNull(),
  eventHash: text("event_hash").notNull(),
  signature: text("signature").notNull(),
}, (table) => [uniqueIndex("idx_audit_id").on(table.id), uniqueIndex("idx_audit_event_hash").on(table.eventHash), index("idx_audit_resource").on(table.resourceType, table.resourceId), index("idx_audit_occurred").on(table.occurredAt)]);

export const exportPackages = sqliteTable("export_packages", {
  id: text("id").primaryKey(),
  requestedBy: text("requested_by").notNull(),
  status: text("status", { enum: ["building", "ready", "failed"] }).notNull().default("building"),
  r2Key: text("r2_key"),
  sha256: text("sha256"),
  signature: text("signature"),
  evidenceCount: integer("evidence_count").notNull().default(0),
  byteSize: integer("byte_size").notNull().default(0),
  errorMessage: text("error_message"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text("completed_at"),
  expiresAt: text("expires_at"),
  assessmentId: text("assessment_id"),
  selectionJson: text("selection_json").notNull().default("{}"),
  excludedCount: integer("excluded_count").notNull().default(0),
}, (table) => [index("idx_exports_requested_created").on(table.requestedBy, table.createdAt), index("idx_exports_assessment_created").on(table.assessmentId, table.createdAt)]);

export const jiraConnections = sqliteTable("jira_connections", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  cloudId: text("cloud_id").notNull(),
  siteUrl: text("site_url").notNull(),
  siteName: text("site_name").notNull(),
  allowedProjectsJson: text("allowed_projects_json").notNull().default("[]"),
  accessTokenCiphertext: text("access_token_ciphertext").notNull(),
  accessTokenIv: text("access_token_iv").notNull(),
  refreshTokenCiphertext: text("refresh_token_ciphertext").notNull(),
  refreshTokenIv: text("refresh_token_iv").notNull(),
  accessTokenExpiresAt: text("access_token_expires_at").notNull(),
  scopes: text("scopes").notNull(),
  status: text("status", { enum: ["active", "reauthorization_required"] }).notNull().default("active"),
  tokenVersion: integer("token_version").notNull().default(1),
  refreshLeaseId: text("refresh_lease_id"),
  refreshLeaseExpiresAt: text("refresh_lease_expires_at"),
  lastTestedAt: text("last_tested_at"),
  lastError: text("last_error"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("idx_jira_connections_user").on(table.userId), uniqueIndex("idx_jira_connections_user_cloud").on(table.userId, table.cloudId)]);

export const jiraOauthStates = sqliteTable("jira_oauth_states", {
  stateHash: text("state_hash").primaryKey(),
  userId: text("user_id").notNull(),
  requestedSiteUrl: text("requested_site_url").notNull(),
  allowedProjectsJson: text("allowed_projects_json").notNull(),
  expiresAt: text("expires_at").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_jira_oauth_states_user_expires").on(table.userId, table.expiresAt)]);

export const jiraUploadReceipts = sqliteTable("jira_upload_receipts", {
  id: text("id").primaryKey(),
  connectionId: text("connection_id").notNull(),
  userId: text("user_id").notNull(),
  deviceId: text("device_id").notNull(),
  evidenceId: text("evidence_id").notNull(),
  issueKey: text("issue_key").notNull(),
  siteUrl: text("site_url").notNull(),
  uploadedAt: text("uploaded_at").notNull(),
  attachmentsJson: text("attachments_json").notNull(),
  receiptSha256: text("receipt_sha256").notNull(),
  signature: text("signature").notNull(),
}, (table) => [
  uniqueIndex("idx_jira_upload_receipts_target").on(table.connectionId, table.evidenceId, table.issueKey),
  uniqueIndex("idx_jira_upload_receipts_sha").on(table.receiptSha256),
  index("idx_jira_upload_receipts_user_created").on(table.userId, table.uploadedAt),
]);

export const jiraUploadOperations = sqliteTable("jira_upload_operations", {
  id: text("id").primaryKey(),
  connectionId: text("connection_id").notNull(),
  userId: text("user_id").notNull(),
  deviceId: text("device_id").notNull(),
  evidenceId: text("evidence_id").notNull(),
  issueKey: text("issue_key").notNull(),
  requestSha256: text("request_sha256").notNull(),
  status: text("status", { enum: ["reserved", "uploading", "succeeded", "failed", "unknown"] }).notNull().default("reserved"),
  leaseId: text("lease_id"),
  leaseExpiresAt: text("lease_expires_at"),
  attempt: integer("attempt").notNull().default(0),
  receiptId: text("receipt_id"),
  lastError: text("last_error"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("idx_jira_upload_operations_target").on(table.connectionId, table.evidenceId, table.issueKey),
  index("idx_jira_upload_operations_status_lease").on(table.status, table.leaseExpiresAt),
]);
